### ISSUE TITLE
STEP BY STEP PLEASE

### ISSUE THREAD

**Issue by Shinnstar** [alzhahir/status#1]
hello, I always use ptero for hosting minecraft servers or whatsapp / telegram bots, I read the readme on this github, but I still don't understand how to do it, I've tried it and it's an error / doesn't work, please make a more detailed step by step.. thank you

**Comment by alzhahir** [comment]
Please refer to [the provided installation steps.](https://github.com/alzhahir/pterodactyl-status#installation) If there are any steps that you don't understand please describe it here.

**Comment by Shinnstar** [comment]
apikey, is it PLTA or PLTC

**Comment by alzhahir** [comment]
If I'm not mistaken, both of them works, but just to be safe, use PLTC. I'll update the documentation later.
